### ISSUE TITLE
Publications working group

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#1]
8 of us just met as the LocalGov Drupal Publications Working Group. 

The notes are here: 
https://docs.google.com/document/d/190RAfMxIcmNYpUK0M9-e2xtP-S9wOHb8vhuu6MGdFHc/edit#heading=h.u61a6fo1wh6g

We also have the working group overview  document that confirms who's in the group, our roles and the aim and domain of the working group: 
https://docs.google.com/document/d/1qgU3Na9i7dyJscbCrXHQy7dDBYCfYLt_ifntxjC2-xs/edit#

We've got another 3 meetings to take this forward and hopefully have something ready to test before the end of the year.

**Comment by rupertj** [comment]
Closing this as I think we're established enough not to need it open any more now.
