### ISSUE TITLE
Warning: Trying to access array offset on value of type null in localgov_publications_tokens_alter() 

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#116]
Fresh install of localgov drupal. 

```
ddev drush si localgov -y;
ddev drush en localgov_demo -y;
ddev drush en workspaces redirect localgov_content_lock  -y;
ddev composer require localgovdrupal/localgov_publications;
ddev drush en localgov_publications -y;
ddev drush uli;
```
Log in, and go to https://localgov.ddev.site/fostering

I see: 

Warning: Trying to access array offset on value of type null in localgov_publications_tokens_alter() (line 26 of modules/contrib/localgov_publications/localgov_publications.tokens.inc).

**Comment by finnlewis** [comment]
Ah - I think this is fixed in the latest 1.x-dev - no release since 8th Sept.

@rupertj @justinepocock any reason not to tag another alpha?

**Comment by rupertj** [comment]
Closing this as there's been a new alpha since this was created.
