### ISSUE TITLE
Estimation of work for publications development work

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#12]
@msayoung mentioned we need to estimate the amount of work to build publications version 1.

Just creating this issue to remind @msayoung and @j4-m to review and estimate. 

We need to know so that we can confirm

- [x] the budget allocated to this working group
- [x] the timeline for development.

**Comment by justinepocock** [comment]
[https://docs.google.com/spreadsheets/d/1bVvvsjcCl787KaC2B8wfhMMkQUvPmn9-nnUJyBCABL0/edit#gid=932656047](https://docs.google.com/spreadsheets/d/1bVvvsjcCl787KaC2B8wfhMMkQUvPmn9-nnUJyBCABL0/edit?authuser=2#gid=932656047)
