### ISSUE TITLE
1.0.0 stable release blockers

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#121]
Just starting this to list out any issues that need to be resolved before tagging a 1.0.0 release.

- [x] https://github.com/localgovdrupal/localgov_publications/pull/119
- [x] https://github.com/localgovdrupal/localgov_publications/pull/117

@rupertj @justinepocock @RyanFH257 what other things?

**Comment by RyanFH257** [comment]
- [x] #122 
- [x] #115 ??
- [x] #94 ??

**Comment by rupertj** [comment]
There's a couple of release blockers for publications in other projects too:
- [x] https://github.com/localgovdrupal/localgov_paragraphs/issues/161
- [x] https://github.com/localgovdrupal/localgov_base/issues/520

**Comment by rupertj** [comment]
All these are done, and there's now a 1.0.0 release!
