### ISSUE TITLE
Cover page reference direction

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#122]
@RyanFH257 mentioned that the direction of entity reference needs to be changed. 

Currently the cover page references the book page node.

He thinks it should link the other direction.

**Comment by finnlewis** [comment]
Discussing this with @ekes  and @RyanFH257 

Currently the workflow is like: 

1. create cover page
2. create book page 1
3. edit cover page and reference book page, save
4. edit book page 1 and save to update the path alias now that it is a child of the cover page.

Clunky!

So: 

**Option 1:** 

Move entity reference field to the book page, referencing cover pages.
Hide the entity reference field unless book depth =1.
Update code that generates path aliases for book pages.

**Option 2:** 

Keep entity reference field where it is.
Add a sudo field to the book page (only display if book depth = 1)
hook_entity_update to 
1. update the cover page node 
2. write the correct url path to the book node

Note: might want to create an entity bundle for this?

@rupertj / @justinepocock / @RyanFH257  penny for your thoughts?

**Comment by rupertj** [comment]
I'm not totally sure if either of those options would work. As the node isn't part of a publication yet, we wouldn't know the book depth to show or hide the field. Plus we'd have to react to the position in the publication being changed in the form, which'd be a faff.

How about option 3:
Add a new form element to the Cover Page node form that lets you choose to add this cover to an existing publication, or a new publication. If "Existing publication" is chosen, we show the existing reference field. If "New publication" is chosen, we create a new publication page behind the scenes and link them up.

**Comment by rupertj** [comment]
Another thing we could do is eliminate the need for step 4 in the original post by updating the path aliases for every node in a publication when the cover page is saved.

**Comment by rupertj** [comment]
@finnlewis Could you try out the code in the attached PR?

It's an implementation of my last suggestion - IE, the path aliases for every node in a publication will now be updated automatically when a cover page is saved.

With this in place, I'd suggest that we can leave the reference field where it is.

**Comment by rupertj** [comment]
Also: this is the last issue left from the list of release blockers.

**Comment by finnlewis** [comment]
Testing now @rupertj

**Comment by finnlewis** [comment]
@rupertj this seems to work nicely in my tests locally. 

1. Create a new publication, 
2. add child pages,
3. see the expected path aliases 
4. Create a new publication landing page
5. Reference the publication in the entity reference field
6. See the url aliases change for the original publication pages. 

One thing that does occur to me is that most people will probably want the old urls to redirect to the new urls.

Can we add a dependency on redirect module to be installed by default? Once installed, it does generate redirects from old path alias to new path alias by default I believe.

**Comment by finnlewis** [comment]
Found a couple of scenarios we might want to consider. 

### 1. Adding multiple publications documents under a cover page.

We currently have the ability to reference multiple publications on a cover page. Testing adding multiple publications, I don't think it updates the url aliases for anything beyond the 1st referenced publication.  

### 2. Changing a publication reference on a cover page.

If we create a cover page, reference a publication, then change the referenced publication, I don't think it updates the url path aliases for the newly targetted publication.

What do you think @rupertj ? Worth covering these?

**Comment by rupertj** [comment]
I think 1 is worth doing. I'd forgotten you can reference multiple publications from one cover, and it's not a big change to support it.

2 is trickier. I'm pretty sure it *should* update the URLs in the publication that's now being referenced (unless there's some cache/hook order thing that stops it)... What it won't do is update the paths on the publication that's now no longer referenced. I'm tempted to say this one's reasonable to expect people to sort out manually.

**Comment by rupertj** [comment]
I'm also temped not to add redirect as a dependency. While I agree that having the redirects in place is the right behaviour, if people want that, they can install redirect. We shouldn't insist that it works that way for them.

Also, in practice, everyone using this module in an LGD site'll have redirect on anyway, as localgov_core has it as a dependency now.

**Comment by rupertj** [comment]
So we've merged the code to update the path aliases on any publication attached to a cover page when the cover page is saved, which makes setting up a publication with a cover page much simpler.

I'm going to close this issue and suggest that if anyone would like to action anything else from this issue, we open a new issue for it.
