### ISSUE TITLE
Remove footnotes until it's stable

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_publications#124]
I've got to the point with footnotes where I'm tempted to take it out and bring it back in a future release once it's more stable.

- It's been the source of all the issues with requiring CK4 on sites using CK5.
- There's a patch for the problems reported in #117 at https://www.drupal.org/project/footnotes/issues/3381366, but the issue queue for the module moves incredibly slowly.
- I've just tried that patch out, and it does seem to fix the issue, but I also can't get a footnote to appear at all now, with or without the patch. (It worked fine last time I tried to use them).
- Ryan's just built the H&F Corporate plan using the dev version of publications, and it doesn't use footnotes.
- I've asked Michael if he's interested in using footnotes, and he said "Its not something we're particularly planning on using, so it'd be no great loss for us."

Is anyone hugely opposed to me taking them out?

**Comment by RyanFH257** [comment]
We can live without for now so fine with me.

**Comment by rupertj** [comment]
Closing as this is now done.
