### ISSUE TITLE
Publication landing page

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_publications#13]
The title page of the publication. 

 - this wants to be optional
 - Maria: this landing page might technically NOT be in the book.
 - users might want to be able to add or remove the landing / title page later
 - Justine: It's a book jacket!

![image](https://user-images.githubusercontent.com/3852805/213467143-06dc94c8-653f-4c18-a868-c7b4e83b8122.png)
https://www.figma.com/file/WkubIZ0JtHpPIAiO5DoQ9B/LocalGov-Drupal-Wireframes?node-id=1301%3A460&t=bUihKoKUeRMOVdxr-0

Examples
https://www.gov.uk/government/publications/disabled-travellers
https://www.gov.uk/government/publications/uk-national-data-strategy

**Comment by finnlewis** [comment]
Also see: 

https://www.gov.uk/government/publications/disabled-travellers

https://www.gov.uk/government/publications/uk-national-data-strategy

**Comment by jbloomfield** [comment]
@RyanFH257 @msayoung @justinepocock 
With the "Documents" section, do we need to reference content as well as PDFs etc?

**Comment by RyanFH257** [comment]
@jbloomfield - yes please. This can be other content types (service page etc) as well as media files such as PDF, Word, Spreadsheets and slide decks

**Comment by msayoung** [comment]
```
Notice: Trying to access array offset on value of type null in localgov_publications_tokens_alter() (line 26 of modules/contrib/localgov_publications/localgov_publications.tokens.inc).
```

I'm getting the above error when creating a publication landing page

**Comment by msayoung** [comment]
The display doesn't seem to align with the wireframe. Is that being tackled elsewhere?

**Comment by finnlewis** [comment]
Moving back to in progress for a bit nore work. 

@rupertj and @justinepocock will take a look at the notice and the layout.

**Comment by justinepocock** [comment]
Additional Tasks: 

- [ ] Make the services references optional configs, so that we don't have a hard dependency on LocalGov_services.

**Comment by justinepocock** [comment]
@msayoung @RyanFH257 

Do we want Page content paragraphs on here? 

Currently we have the body with summary field and a page content paragraph with image, numbered text and text in. 

It feels unnecessary as this content type won't have 'that kind' of content on it.

**Comment by RyanFH257** [comment]
No, body and summary are fine.

If we do match it up to the GOV.UK examples then the documents should be displayed first and then body afterwards.

https://www.gov.uk/government/publications/disabled-travellers

https://www.gov.uk/government/publications/uk-national-data-strategy

**Comment by justinepocock** [comment]
For the banner is it ok to reuse the localgov_base  banner primary template here?

The design shows the banner block aligned to the right but for ease/reuse as it's the same paragraph as the primary banner reusing the tpl makes some sense. 


![Image](https://github.com/localgovdrupal/localgov_publications/assets/638213/286f3c53-34ae-4fdc-a308-c5653d97b8ac)

**Comment by justinepocock** [comment]
I'm not sure the best was to do the document previews for the PDFs. 

Do we want to use something like https://www.drupal.org/project/pdfpreview or do we expect users to add their own thumbnail on another field - feels like a step too much but then the module feels like too much because imagemagick... oh I dunno the heat is getting to me, anyone got any thoughts? 

I'm going to use the SVG from gov.uk for the HTML thumbnail.

**Comment by RyanFH257** [comment]
@justinepocock - regarding the banner, yes that's fine

Document thumbnails, I'm inclined to keep it simple for now and re-use the GDS SVGs. There are 3 for the different doc types

![image](https://github.com/localgovdrupal/localgov_publications/assets/84503265/ccc13995-2c23-441f-99d0-6bdfbbdddeee)

**Comment by justinepocock** [comment]
Great minds, I've literally just stolen them all from GDS to pop them in, councils can override this easy enough however they see fit.

**Comment by finnlewis** [comment]
From meeting today: tasks remaining:

- [ ] Add the xls / csv icon @justinepocock 

Discussing the 'Author link' which is in the wire-frame. Neither Michael or Ryan thinks this is necessary. We can use the service link for publications that are linked to a service and the body text field can be used for other things.

Drop the author link field!

**Comment by RyanFH257** [comment]
Discussed in the last meeting to put the services link to one side for now. Need to better understand how other councils would want to use this. Michael and I felt that the link going back to a service section page would lead people in circles and may be should go to a listing of all publications tagged to that service section.

**Comment by RyanFH257** [comment]
@justinepocock 

Updates 

- [x] Need to be able to link to multiple files and pages
- [x] Publish date information should all be in one line and the time removed
- [x] Link text for files should show the descriptive name
- [x] Link text for all document links should be big - font-size: x-large
- [x] Body text and document link width to be constrained
- [x] Remove visually hidden label 'Document' on files

**Comment by justinepocock** [comment]
https://github.com/localgovdrupal/localgov_base/pull/502

**Comment by justinepocock** [comment]
Inline fields https://github.com/localgovdrupal/localgov_base/pull/504 and 503 (waiting to see if time removing is a core thing or not)

**Comment by rupertj** [comment]
Closing this as it's all done!
