### ISSUE TITLE
Book content type is present on a new install

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#140]
As we depend on book module, installing localgov_publications adds the book content type.

Ideally, if we don't have the book module installed, installing localgov_publications would ideally not add the book content type.

@stephen-cox how have we done this elsewhere?

Maybe https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Extension%21module.api.php/function/hook_modules_installed/8.9.x

**Comment by finnlewis** [comment]
Passing to @rupertj in the hope we can include this in an initial release.

**Comment by rupertj** [comment]
I'm going to pass this over to @joachim-n to take a look at.

Just for clarity:
localgov_publications has book as a dependency. We think the Book content type that book module creates will confuse people who have just enabled localgov_publications.

1) For sites that were already using book when localgov_publications was enabled, we'd like the Book content type to remain in place.

2) For sites that were not already using book when localgov_publications was enabled, we'd like the Book content type to be deleted.

**Comment by joachim-n** [comment]
> For sites that were not already using book when localgov_publications was enabled, we'd like the Book content type to be deleted.

More precisely, do you mean 'not installed'?

I've found a reasonably elegant way to do this, which involves putting a copy of `node.type.book.yml` into the localgov install profile, with a dummy module dependency which can't be satisfied. The profile's version overrides book module's, and then the config system won't install it because 'made_up_module_to_prevent_installation_of_this_config' doesn't exist.

However, this means that this could happen:

1. User installs localgov, with no intention of using localgov_publications
2. User installs book module
3. Book node type is not installed!

Is this acceptable?

If not, the next thing to try is https://www.drupal.org/project/config_filter

**Comment by joachim-n** [comment]
The config_filter module isn't going to help here -- it only acts on config import and export, and this is something else: a config install.

**Comment by rupertj** [comment]
I don't think we should do anything in the profile for this. Most of the sites that this'll module'll be installed on already exist. Also we don't want to block people from ever using book module if they wish to.

Not ever installing the book content type would be great, but installing it with the book module and then immediately removing it would be fine.

Is there no way to do this with Finn's suggestion of hook_modules_installed?

**Comment by joachim-n** [comment]
I was wary of that given what the docs say, but since we're not syncing and I'm out of cleaner options, I've given it a go and it seems to work!

**Comment by joachim-n** [comment]
MR: https://github.com/localgovdrupal/localgov_publications/pull/144

**Comment by joachim-n** [comment]
Oh wait I just remembered why I originally thought hook_modules_installed() wouldn't work -- it's fine if you're installing localgov_publications locally, but if you do that and the deploy to prod to deploy the module being enabled, it becomes a sync operation.

I'm not sure whether in that case, book module's config would be installed or not. I'll need to experiment with the deployment process.

**Comment by joachim-n** [comment]
I've tested this with a config import and it works OK.

**Comment by rupertj** [comment]
This is now fixed
