### ISSUE TITLE
Text format - add auto heading ids to WYSIWYG text format.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#142]
We've moved to paragraphs in the publication content.

This means we cannot set our custom input format which would include the auto heading ids plugin.

Discussing with @rupertj , we think the best thing to do it add a hook_install or similar to add the plugin to the existing WYSIWYG text format. 

This will be altering existing config, but will only result in adding ids (if not already present) to headings, which might have other benefits (@msayoung ?).

CC @andybroomfield and @willguv for awareness and comment.

Passing to you @rupertj to implement, such that we can have a table of contents on a fresh install.

**Comment by andybroomfield** [comment]
This would be layout paragraphs, so using the localgov_paragraphs?
It makes sense to have a single editor format for consistency.
Does [auto heading IDs](https://www.drupal.org/project/auto_heading_ids) conflict with [anchor link](https://www.drupal.org/project/anchor_link)?

**Comment by rupertj** [comment]
So it looks like aurto heading IDs will overwrite existing IDs, which is annoying. I just put this markup in a publications page:
```
<h2 id="something-else">This is another header</h2>
```
And got this out:
```
<h2 id="this-is-another-header">This is another header</h2>
```
So I don't think we could roll this out everywhere as-is. We'd either need to change the module to stop it overwriting existing IDs, or make our own filter that works like that.

**Comment by finnlewis** [comment]
@rupertj is suggesting we improve the plugin to NOT override existing id's in headings. We could then inclide our own version of this plugin in localgov_publications or improve the plugin at https://www.drupal.org/project/auto_heading_ids

**Comment by rupertj** [comment]
Closing this as it's merged :)
