### ISSUE TITLE
HTML pubs documentation

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_publications#149]
HTML pubs is ready to be installed by councils

https://github.com/localgovdrupal/localgov_publications

The current documentation is limited and accessed via Slack

https://localgovdrupal.slack.com/canvas/C01T8DVDJTW

We need to:

- move it to the docs site
- ask a content designer (Ben?) to sense check
- add a how to video

Will is talking to Hammersmith & Fulham about the best way to deliver the above

**Comment by willguv** [comment]
Great documentation by @LizziCBFC 

[Creating a publication.docx](https://github.com/localgovdrupal/localgov_publications/files/14701716/Creating.a.publication.docx)

**Comment by finnlewis** [comment]
From a Tech Governance perspective, we would like to define some 'gates' that LGD modules should aim to pass and self assess or opt-in.

So far, we've identified:

- Accessibility review
- Automated test coverage
- Documentation
- Security

We have not yet confirmed specifics yet, but we'll get a set of check lists that people can use to assess. 

From a documentation perspective, this could be something like: 

- [ ] The project has a README that includes: the purpose of the module, how to install and use the module, the maintainers, how to contribute...
- [x] The project has a documentation page on [docs.localgov](https://docs.localgovdrupal.org/) (with x,y,z info)
- [x] The project has a how-to video demonstrating basic setup and usage.

What else might we want? CC @msayoung

**Comment by willguv** [comment]
Any more on these gates @finnlewis thanks

**Comment by willguv** [comment]
Covered here - thanks @aaronhirtenstein 

https://docs.localgovdrupal.org/content/features/publications.html

Considering this done for now
