### ISSUE TITLE
Paragraph: numbered sections

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_publications#15]
@RyanFH257 requested that publications have a new content type which would allow:

Text - with the option to add paragraph numbers like [Buckinghamshire](https://www.buckinghamshire.gov.uk/your-council/contact-and-complaints/feedback-compliments-and-complaints-policy/compliments-complaints-annual-update/stage-1-corporate-complaints/) and an optional coloured background and border - this is for examples and case studies.

![image](https://user-images.githubusercontent.com/3852805/202691945-282cb1c5-b9ff-4099-8bdf-09726f3b02d1.png)

**Comment by msayoung** [comment]
Split out from https://github.com/localgovdrupal/localgov_publications/issues/6

**Comment by msayoung** [comment]
Number field & text field. 

Not automatic numbering. 

Could generate the table of contents?

**Comment by andybroomfield** [comment]
Question. Is this paragraph particullar for Publications or is it something all sites could use (like subsites)?
Should we be making paragraphs in each module or moving them to localgov_paragraphs?
(Guess that is a wider discussion)

**Comment by msayoung** [comment]
Great point @andybroomfield 

Lets move this to localgov_paragraphs

Any thoughts on whether it should be in the main or sub modules?

**Comment by finnlewis** [comment]
Task remaining: 

- [x] remove the numbered text paragraph from here and add it to localgov_paragraphs.

**Comment by finnlewis** [comment]
@justinepocock @rupertj I'm looking at this now 😄

**Comment by finnlewis** [comment]
I think this is done. 

- https://github.com/localgovdrupal/localgov_paragraphs/pull/147
- https://github.com/localgovdrupal/localgov_publications/pull/88
