### ISSUE TITLE
Link Cover Page icons

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_publications#166]
The icons on the cover pages should link to the Publication(s)/Document(s) as they do on GOV.UK pages (example: https://www.gov.uk/government/publications/domestic-licensing-application-guidance)

**Comment by zackdavies** [comment]
PR created for this: https://github.com/localgovdrupal/localgov_publications/pull/199/files

(One test has failed, but this is to do with Composer issues, which I don't think are related to my changes)

**Comment by AWearring** [comment]
@markconroy 
RE: https://github.com/localgovdrupal/localgov_publications/pull/199#issuecomment-2331677636
> I'm going to merge this, because it follows the same pattern we have for teasers and cards, but we should think about how we'd design a pattern that will not have 2 identical links side by site. In this case we have:
> 
> ```
> <a href="linkt-to-the-file>
>   <svg>...</svg>
> </a>
> <a href="linkt-to-the-file>
>   <media-item>...</media-item>
> </a>
> ```
> 
> This means screenreaders will read out the link twice.

I see that gov.uk get round this by adding `tabindex="-1"` and `aria-hidden="true"` to the <a> tags: see [This example gov.uk page](https://www.gov.uk/government/publications/domestic-licensing-application-guidance)

**Comment by markconroy** [comment]
Oh, that's a lovely simple solution.

I'll create a follow up for us - #205
