### ISSUE TITLE
Unable to save WYSIWYG text format: 'keep_existing_ids' is not a supported key.

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_publications#177]
When trying to save the WYSIWYG text format there's an error showing which prevents saving the format:

'keep_existing_ids' is not a supported key.

This also prevents people from uninstalling the module as when trying to uninstall the following error is shown

Provides a filter plugin that is in use in the following filter formats: <em class="placeholder">WYSIWYG</em>

But we can't save to filter format to remove the filter plugin.

**Comment by finnlewis** [comment]
Discussing in Tech Drop-in, Joe @ Blackburn and Phil @ Northumberland both reported this issue too!

**Comment by stephen-cox** [comment]
Closing as a duplicate of #177
