### ISSUE TITLE
Dependency on deprecated "Book" module

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/localgov_publications#180]
This module depends on the deprecated `drupal:book` module https://www.drupal.org/node/3223395#s-book

Are there plans to not depend on this module that will no longer be part of the core in Drupal 11

**Comment by rupertj** [comment]
We'll have to stop depending on the core version of book and depend on the contrib one instead, which I suspect means I'll need to make a new major version of localgov_publications to do that.

**Comment by rupertj** [comment]
I've started a 2.x branch for Drupal 11 onwards: https://github.com/localgovdrupal/localgov_publications/tree/2.x

**Comment by andybroomfield** [comment]
[Contrib book](https://www.drupal.org/project/book) works on d10 also so we could move 1.x to that.

**Comment by rupertj** [comment]
I hadn't thought of that. Is it possible to install it while core book is still in place?

**Comment by andybroomfield** [comment]
I think so, though internally the namespace of functions / services might have changed...

**Comment by rupertj** [comment]
I've just tried this out and it works! So I'll bin the new 2.x branch and make 1.x use contrib book.

**Comment by rupertj** [comment]
Closing as this is done.
