### ISSUE TITLE
SIngle page publication shows menu block

### ISSUE THREAD

**Issue by AWearring** [localgovdrupal/localgov_publications#190]
We have a single page publication (https://www.n-kesteven.gov.uk/business-services-support-licensing/licensing/business-licences-conditions/wheelchair-accessible-taxis/designated-list-wheelchair-accessible-0) that is showing the menu block even though there are no children.

In https://github.com/localgovdrupal/localgov_publications/blob/1.x/src/Plugin/Block/PublicationNavigationBlock.php from line 114 I can see that this is not expected behaviour

```
    // If the top level doesn't have any child pages, (IE this is a single
    // page publication) don't show the menu block, as there isn't anything
    // else to navigate to.
 ```

**Comment by AWearring** [comment]
Hi @rupertj 
This issue was introduced in [1.0.5](https://github.com/localgovdrupal/localgov_publications/releases/tag/1.0.5) - rolling back to 1.0.4 resolves this issue. Therefore, I'm guessing that it'll be something in the changes you made in https://github.com/localgovdrupal/localgov_publications/pull/188 that is causing the issue.

**Comment by rupertj** [comment]
Thanks @AWearring! I've fixed the issue and improved the test that was meant to check if the block showed up or not, but didn't actually check anything.

(It was checking that the ID of the block that we used to use there didn't appear on single pages, but of course as we no longer use that block, the ID wasn't there anyway and the test passed. The tests now check for the title not being there, and there's a corresponding check for the title being there on multi-page publications to guard against the title changing.)

**Comment by AWearring** [comment]
@rupertj Fab, many thanks :-)

**Comment by rupertj** [comment]
Fixed!

**Comment by rupertj** [comment]
And I've made a new release (https://github.com/localgovdrupal/localgov_publications/releases/tag/1.0.6) with the fix in.
