### ISSUE TITLE
Cover page icons + file link causes duplicate links

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_publications#205]
Follow-up from #166 

We are now linking our icons and files for cover pages. This means we have 2 identical links side-by-side, which we should not have for accessibility purposes.

@AWearring says:

> I see that gov.uk get round this by adding tabindex="-1" and aria-hidden="true" to the tags: see [This example gov.uk page](https://www.gov.uk/government/publications/domestic-licensing-application-guidance)

Let's do the same.

**Comment by AWearring** [comment]
PR to resolve: https://github.com/localgovdrupal/localgov_publications/pull/206

**Comment by rupertj** [comment]
Closing as I've merged the PR. Thanks!
