### ISSUE TITLE
Add LocalGov standard Github workflows for CI tests

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#25]
Just a note to self to add our standard CI config. Possibly from the profile. 

CC @stephen-cox

**Comment by rupertj** [comment]
Can we close this? I'm pretty sure we can, but I'm conscious that I fixed it, so I'd like someone else to confirm that I did it correctly :)

**Comment by rupertj** [comment]
No news is good news, right?
