### ISSUE TITLE
Default all publication pages to be part of a book

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#33]
@rupertj was thinking about defaulting all publications to be part of a book.

Rather than having to use the book widget, we could default new pages to be in a book.

**Comment by andybroomfield** [comment]
This confused me when I was just testing this.
I assumed that by creating a publication landing page, this would create the publication.
Instead I have to create a book in the publications outline.

**Comment by rupertj** [comment]
This has also confused me. There's been a few times now that I've forgotten to make a new publication page into a publication.

For the moment I've added some validation to ensure people always make the choice. If you try to create a new publication page without it being part of a publication, you'll get this:

<img width="1225" alt="Screenshot 2023-11-15 at 12 54 44" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/1967b3e3-3e57-43bd-91ea-528f6e06c931">

**Comment by rupertj** [comment]
This is merged now, I'm going to close the issue.
