### ISSUE TITLE
Rename book to publication on node forms

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#39]
When we're on a localgov_publication_page , it would be good to refer to publications rather than books. 

Shall we / can we rename the book parent widget title and options to 

Book => Publication
Book outline => Publication outline
Not in book => Not in publication
create new book - => - create new publication - 

and any other places where the word 'book' is used.

![Image](https://user-images.githubusercontent.com/326588/226415952-5b7d5cb0-98c5-4836-a680-569104537141.png)

![Image](https://user-images.githubusercontent.com/326588/226415503-ea186971-9bf6-4413-9273-41d57ba7eaf5.png)

**Comment by rupertj** [comment]
I've been testing the alpha and can't see any mentions of books on the node form. (I did find one on a different page, but I'll raise that as a new issue).
