### ISSUE TITLE
Single page display

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#4]
## User stories

As an Editor I want to choose a single page display for some of my publications, so that citizens can read it in one go
As a citizen I want to see the section titles in a Table of contents so I can jump to the right section
As an citizen I want the page headings (html) to be correct  so that I can properly understand the content structure

## Acceptance tests
Edit the top level page of a book
In the "Display options" field choose the "single page" option
Save

View this page, see all the child pages printed out in the right order, with the correct heading heirarchy.
See a table of contents in the sidebar generated from the node titles. Links to heading on the page.

### Questions
what do do with the original node URLs ( rabbit hole? Redirects ) 
how to cleverly alter the HTML structure ? H1 of "section" becomes H2, and H1 of "subsection" becomes H3 etc. Will also need to alter the headings within the page so they appropriately nested. could quickly run out of heading levels.

**Comment by msayoung** [comment]
Question: what is the motivations for this approach, rather than using a single node an autogenerating a Toc from the page heading?

**Comment by rupertj** [comment]
I'm going to close this one, as we've figured out how to do single page publications (IE just create one page) and we did exactly what Maria suggested to generate the ToC from the headings.
