### ISSUE TITLE
Specification for the publications

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#5]
Creating this issue to track and confirm our specification for the publication user stories, wire-frames and overall specification. 

See 

- https://miro.com/app/board/o9J_lHm9M2s=/
- https://www.figma.com/file/WkubIZ0JtHpPIAiO5DoQ9B/LocalGov-Drupal-Wireframes?node-id=1301%3A374

**Comment by msayoung** [comment]
To define:

- Publication content type ( https://github.com/localgovdrupal/localgov_publications/issues/7) 
- Publication management (distinct from other Books) ( https://github.com/localgovdrupal/localgov_publications/issues/8 )
- Navigational heirarchy ( https://github.com/localgovdrupal/localgov_publications/issues/9 ) 
- Optional displays ( #4 ) 
- Publication landing page https://github.com/localgovdrupal/localgov_publications/issues/13
- Integration with localgov_workflow https://github.com/localgovdrupal/localgov_publications/issues/14
- Available paragraphs and layouts ( #6 )

**Comment by finnlewis** [comment]
We think can be closed for now. Nothing to be done, but good for reference to the other specs.

Thanks @msayoung !
