### ISSUE TITLE
Body text field - do we need it?

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#51]
At the moment, we have a body field in the publication page: 

![Image](https://user-images.githubusercontent.com/326588/228849194-fd892d17-69b9-496c-85d6-ae24ea9cb1fc.png)

The suggestion is to 

- [x] remove the body field 
- [x] make a default text paragraph, opened, so it looks like the body field and is easy to

**Comment by msayoung** [comment]
great
