### ISSUE TITLE
Page title block - H1 of top page (plus published date?)

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#52]
Looking at H1's in the wireframes, we need to add a title block to the publications pages that displays the title of the top level page. 

This will be more like Bucks: https://www.buckinghamshire.gov.uk/your-council/contact-and-complaints/feedback-compliments-and-complaints-policy/compliments-complaints-annual-update/benchmarking-with-other-authorities-2/

than the ico: 
https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/principles/data-minimisation/

Questions about last updated: 

We have the published date and updated date on each publication page node. 

In the title block, the wireframe displays the published and last updated dates. Should these be the whole publication   or for the current page? 

For now: 
 - display the date published and last updated of the top level page in the title block.
 

https://www.figma.com/file/WkubIZ0JtHpPIAiO5DoQ9B/LocalGov-Drupal-Wireframes?node-id=1301-374

**Comment by rupertj** [comment]
The H1 shows the title of the top level publication now, which is good.

What I don't think works is that the title of the page you're viewing isn't shown any more. EG:
<img width="1153" alt="child_page" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/75d24b0f-ebff-4065-91bf-b1f57cf4d788">

The node being viewed here is the first child in the publication, called "This is a child page". While making this publication I got briefly confused about which page I was looking at, because there's very little to indicate that you're looking at this page.

The wireframes look like they have the page title for child pages above the content, and bold on the current menu item.

**Comment by finnlewis** [comment]
So we need to add the node title to the current page. 

Tasks: 

- [ ] Add the node title to every publication page as an H2. Positioned above the node content, like on [Bucks](https://www.buckinghamshire.gov.uk/environment/sustainability-and-climate-change/energy-and-climate-change/the-climate-change-and-air-quality-strategy/climate-change-and-air-quality-strategy/the-councils-emissions/)

**Comment by rupertj** [comment]
There's a fix for the missing node title here: https://github.com/localgovdrupal/localgov_publications/pull/82

**Comment by RyanFH257** [comment]
The use of H1s and H2s in guides is really hotting up and will likely have implications for Publications, depending on the road we go down. There is a growing desire for the H1 on guide pages to be the page title and not the title of the guide overview.

I'm in agreement with this and feel the same needs to happen with Publications.

@msayoung and @finnlewis - this is how it appears to be in the [Community Shares Handbook](https://www.uk.coop/resources/community-shares-handbook-cs), so is this something we can replicate?

**Comment by justinepocock** [comment]
Maria suggested we can use a heading group to wrap both h1s and make it like the NHS example https://www.nhs.uk/conditions/acute-pancreatitis/causes/ 

There's no strong accessibility semantics but it could be worth looking at. 

And don't forget a visually hidden colon

**Comment by rupertj** [comment]
<img width="1184" alt="Screenshot 2023-08-17 at 13 18 39" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/eafa04c0-b708-431e-a2bd-bec39e207c9e">

**Comment by rupertj** [comment]
Markup looks like this:
```
<div class="lgd-page-title-block">
  <h1 class="lgd-page-title-block__title">
         <span>
        Child page of a publication
        <span class="visually-hidden"> - </span>
      </span>
      <span role="text" class="lgd-page-title-block__publication-title">Ru's test publication</span>
  </h1>
</div>
```

**Comment by finnlewis** [comment]
@rupertj has done most of this. @justinepocock is working on a pull request which will cover the rest: https://github.com/localgovdrupal/localgov_publications/pull/85

**Comment by rupertj** [comment]
Closing as done.
