### ISSUE TITLE
 Warning: Trying to access array offset on value of type null in localgov_publications_form_alter

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#59]
On a fresh install, enable localgov_publications, go to
https://localgov.lndo.site/node/add/localgov_publication_page

I see this: 

> 
> Error message
> Warning: Trying to access array offset on value of type null in localgov_publications_form_alter() (line 119 of modules/contrib/localgov_publications/localgov_publications.module).
> 
> localgov_publications_form_alter(Array, Object, 'node_localgov_publication_page_form') (Line: 562)
> Drupal\Core\Extension\ModuleHandler->alter('form', Array, Object, 'node_localgov_publication_page_form') (Line: 838)
> Drupal\Core\Form\FormBuilder->prepareForm('node_localgov_publication_page_form', Array, Object) (Line: 282)
> Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
> Drupal\Core\Controller\FormController->getContentResult(Object, Object)
> call_user_func_array(Array, Array) (Line: 123)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)
> Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
> Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)
> Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)
> Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
> Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
> Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
> Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
> Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
> Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
> Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
> Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)
> Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
> 
>

**Comment by rupertj** [comment]
Hi @finnlewis - This fixes the issue for me. Could you confirm if it fixes it for you? Ta.

**Comment by finnlewis** [comment]
Yup, lovely, thanks @rupertj  :)
