### ISSUE TITLE
Publications paragraphs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#6]
Which paragraphs will we have available by default at the start of publications? 

note: @RyanFH257 mentioned footnotes as a thing

**Comment by msayoung** [comment]
@RyanFH257 - could you let me know you expectations / hopes / dreams about the kinds of paragraphs we'll have available? 

My thoughts so far
- Text
- image with caption
- new: something for graphs 
- tables
- Quote

I think you mentioned last time the possibility of multi column layouts. This would be good to consider up front. 

Footnotes: initial thoughts is the they could make the single page view more complicated (assuming we want them at the bottom), though I'm sure we could work it out. ( cc @markconroy )

**Comment by RyanFH257** [comment]
@msayoung yes all of those plus videos and media with text.

- Text - with the option to add paragraph numbers like [Buckinghamshire](https://www.buckinghamshire.gov.uk/your-council/contact-and-complaints/feedback-compliments-and-complaints-policy/compliments-complaints-annual-update/stage-1-corporate-complaints/) and a coloured background and border - this is for examples and case studies.

- Charts and graphs - again like Bucks with the ability to switch between a chart view and table view to make the data more accessible. This is something I've been talking to Justine about. If we have to upload a chart as an image, it would be good if we could upload them as SVGs so they retain the same quality no matter what screen resolution or size they are viewed at.

**Comment by andybroomfield** [comment]
Is there a reason not to enable the same ones as subsites?

**Comment by markconroy** [comment]
In terms of consistence, I'd prefer the same paragraphs in each content type. If "this" content type needs components, it gets the range of components available.

**Comment by msayoung** [comment]
I'm not convinced we should add them  all by default. There are sometimes cases when we might want to restrict which are available to encourage best practice / a particular design pattern. (as we do in service pages).

Having said that, in this case I don't have a particular objection other than the inevitable complexity of ensuring everything works in every combination. 

( btw @markconroy , in microsites and localgov_page we're only offering a subset of paragraphs that are available on subsites)

**Comment by finnlewis** [comment]
@benhillsjones is keen to restrict paragraphs to avoid content designers using more complex web based paragraphs (slideshows / acordians etc. ) - the purpose of this is to get the print style content onto the web in an accessible format

**Comment by finnlewis** [comment]
We might also need to consider how paragraphs render when printing or exporting as a PDF.

More complex interactive paragraphs like accorions will need some extra work to ensure the content renders out clearly in print / PDF.

**Comment by msayoung** [comment]
I'm tempted to keep the dependencies light so either define none (and therefore allow all) or just image and text from localgov_paragraphs and let people add more if they like. 

Quotes and Tables are in the subsites `localgov_subsites_paragraphs` so these can be enabled if required

**Comment by finnlewis** [comment]
@msayoung suggesting keeping it super simple initially:
 - add dependency on localgov_paragraphs
 - include text and image by default.
 
Then allow others to be configured by site builders later and/or add more fancy paragraphs later.
