### ISSUE TITLE
Table of contents is displayed for single page publications

### ISSUE THREAD

**Issue by j4-m** [localgovdrupal/localgov_publications#60]
The ToC is pretty useless when there's only a single page in the publications so we should hide it.

- [ ] Create tests to demonstrate bug/issue
- [ ] Implement the fix

**Comment by rupertj** [comment]
I've just tried out building a multi-page and single page publication and both seem fine to me. The ToC is useful as jump links down the page on the single page publication and the book nav only shows up on the multi page one.

<img width="1160" alt="multi_page" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/e6fd25ba-bf14-4b1c-aae0-3cbe7d02ca26">
<img width="1176" alt="single_page" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/175bb21d-a156-4483-9a78-59cef2dd5345">

**Comment by finnlewis** [comment]
We think this is working now.
