### ISSUE TITLE
Path aliases for publication book pages and publication landing pages

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#61]
We need automated path aliases!

Publications landing page: 
 - default to /publications/{title}
 

Publication book page: 

 - If a publication book page has a publication landing page
 -  default to /publications/{landing-page-path-alias}/{book-page-title-with-parents}

Questions: 
 - what happens the publication landing page changes url alias?

**Comment by j4-m** [comment]
To facilitate this we will add a reference field to the Publication landing page which allows the reference of the Publication top-level page.
