### ISSUE TITLE
Publication not selected on existing publications

### ISSUE THREAD

**Issue by j4-m** [localgovdrupal/localgov_publications#67]
When revisiting an existing publication page which was previous made the 'top-level' page I am presented with this:

![image](https://user-images.githubusercontent.com/11015602/236210783-3882e640-7853-4d3f-b940-bf47cf188c5d.png)

To reproduce:
1. Create a publication page and choose 'Create a new publication'
2. Save
3. Return to the form

**Comment by rupertj** [comment]
I've fixed this in the linked PR. The code to change "Book" to "Publication" was setting the label of that option when it shouldn't have.
