### ISSUE TITLE
Use Layout paragraphs

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_publications#74]
On a default install with just localgov_publications installed. I just see the classic style paragraph widget.

Is the plan to use Layout paragraphs?

**Comment by justinepocock** [comment]
Yes, if I get time today I'll get this in

**Comment by finnlewis** [comment]
@rupertj mentioned this today. 

We're very close to releasing a 1.0.0 release. 

Should we try to add layout paragraphs before releasing 1.0.0 ?

@willguv any steer from content designers? 

@msayoung any steer from an accessibility perspective?

@markconroy any thoughts?

**Comment by andybroomfield** [comment]
It's posible for site builders to make this change themselves by changing it in manage form display.
My question above was if this was a deliberate choice for publications to enforce a one column style, which building out through classic paragraphs can be simpler.

**Comment by markconroy** [comment]
From the kinds of PDFs our clients usually have, I think they would like (demand) a paragraphs type approach, so turning on layout_paragraphs seems like a sensible default for me.

**Comment by justinepocock** [comment]
Yes layout paragraphs makes sense. There's some work to do around layout and sidebars and needing more space to be extra jazzy but it's not a blocker. 


https://www.lbhf.gov.uk/publications/corporate-plan/hf-plan-2023-2026/our-borough-glance

**Comment by rupertj** [comment]
Closing this as we're now using layout paragraphs.
