### ISSUE TITLE
Drupal 10 - test localgov_publications in D10

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#76]

**Comment by finnlewis** [comment]
Test with CKEditor 4 and 5 enabled at the same time?

**Comment by rupertj** [comment]
I've done some testing! I've also fixed all the small issues I ran into while enabling and using the module. The dev version of this'll now install on LGD3.x and work.

The issues I found while testing are:

1. The Publications format uses CKEditor, not CKeditor 5 by default. You can just edit the format and change it to CK5 and it works though.
2. The footnotes display a bit funny. They do seem to work though:
<img width="1164" alt="Screenshot 2023-08-16 at 17 05 56" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/f85987a0-837b-451e-8bf8-07102e134aa8">

**Comment by rupertj** [comment]
I'm going to close this, as now we've dropped support for D9, we're only testing in D10.

Also, all the issues identified in this issue are solved by removing footnotes in #124.
