### ISSUE TITLE
No link to root of publication in menu

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#79]
In the publication menu, there is no link to the top level root publication page.

![Image](https://github.com/localgovdrupal/localgov_publications/assets/326588/12902e40-e5de-4816-99aa-ea79dec579bc)

Feels like there should be, no?

**Comment by RyanFH257** [comment]
Was agreed at the last meeting that this should be included in the menu

**Comment by rupertj** [comment]
I've made a fix for this:

<img width="1183" alt="Screenshot 2023-11-02 at 09 56 16" src="https://github.com/localgovdrupal/localgov_publications/assets/326243/894a62a8-adec-4952-9600-51e449e07be0">
