### ISSUE TITLE
Publication management

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_publications#8]
As an Editor I can visit /admin/structure/publications to see all my publications so that I can manage them
As an Editor I can visit /admin/structure/books to see all the books _excluding_ the publications 

## Acceptance tests

- Create a publication page
- Visit /admin/structure/publications
- See a list of all publications
- See a link to  Edit and order titles
- Clicking this link shows the book outline and allows you to reorder and rename publication page titles, and shows the Operations View, Edit, Delete for each one.

**Comment by j4-m** [comment]
It got merged!

https://github.com/localgovdrupal/localgov_publications/pull/45
