### ISSUE TITLE
Publication navigation

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_publications#9]
## User stories

As a citizen 
- I want to see the book outline as a persistent ToC 
- I want to see where I am in the heirarchy
- I want to jump straight to a later section / subsection 
- I want to easily navigate to the next page
- I want to easily navigate to the previous page
- I want to see the Publication name as a persistant banner so that I know I'm still within the book

## Acceptance tests

Assuming there is a book with multiple levels of pages. 

Visit the top level page. 
See the Publication name (the top level page name) in a banner
See the book outline in the sidebar with the sections exposed (1st level, no children exposed)
See a link to the first child page with the label "Next: Page title"
There will be no previous item

![image](https://user-images.githubusercontent.com/3852805/198276022-4aeb2ab6-f74d-44c0-8a07-8d4add81c823.png)

Click on a 1st level item in the book outline
See the Publication name (the top level page name) in a banner
See the book outline in the sidebar with the sections exposed
See the child items of this page exposed and indented
See the current page highlighted in the book outline
At the bottom of the page see a link to the previous page with the label "Previous: page title"
At the bottom of the page see a link to the next page (the first child) with the label "Next: page title"

![image](https://user-images.githubusercontent.com/3852805/198276436-ead6923f-dffe-4d61-b12b-f143e21810f4.png)

**Comment by finnlewis** [comment]
@rupertj raises the UX of creating a 'book' - clunky.

 - Suggesting automating adding the content type to a book, to make it easier for content designers. 

We might spin this out to another issue though.

**Comment by jbloomfield** [comment]
@msayoung @finnlewis @rupertj 
So currently the TOC block in the left sidebar "On this page" shows links for H2 titles added to the current page.

The wireframes added to this ticket suggest that the TOC would list a landing page and any child pages with navigation at the bottom for previous/next. 

What is the case here, please?

**Comment by jbloomfield** [comment]
@rupertj @finnlewis @msayoung 
I think I have answered my own question.

<img width="1171" alt="Screenshot 2023-03-17 at 14 24 37" src="https://user-images.githubusercontent.com/869070/225932601-e4c5cb01-f1fb-4c33-9a31-091eea140dd4.png">

So the top block on the left is the "Book navigation" block and the "On this page" block is the H2 auto-generated headings

**Comment by msayoung** [comment]
Yes, thats right !
@jbloomfield

**Comment by finnlewis** [comment]
Also see https://github.com/localgovdrupal/localgov_publications/issues/79

**Comment by rupertj** [comment]
Closing as done.
