### ISSUE TITLE
Add to localgov_demo with demo content

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_publications#91]
It would be great to be able to demo this rapidly in localgov_demo with some fleshed out demo publications.

**Comment by stephen-cox** [comment]
PR adding the module here https://github.com/localgovdrupal/localgov_demo/pull/124

Will still need to add demo content for pubs.

**Comment by rupertj** [comment]
Closing this issue, as the demo content for pubs was added in https://github.com/localgovdrupal/localgov_demo/pull/129
