### ISSUE TITLE
Machine name of the Publication landing page should be 'localgov_publication_landing_page'

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_publications#93]
Currently it's 'publication_landing_page', which is inconsistent with the Publication page - 'localgov_publication_page'.

This also means that other parts of localgov which check for the 'localgov_' prefix on content type names don't work with it. localgov_workflows_node_type_insert() / localgov_workflows_install() is one example of this.

**Comment by rupertj** [comment]
So I've had to take this a bit further than planned. My proposed name for the content type of 'localgov_publication_landing_page' is 33 chars long, and Drupal has a limit of 32 chars for that field.

I was going to go for 'localgov_publication_landingpage', but @justinepocock suggested 'localgov_publication_cover_page', which we both thought was a better name for what this content type is.

I've gone through and replaced any mention of "Publication landing page" in the codebase with "Publication cover page". As this isn't just a code change, I'd like to hear what people think of it.

**Comment by finnlewis** [comment]
Sounds perfectly reasonable to me! Thanks @rupertj  :+1:

**Comment by willguv** [comment]
How about “publication overview” to follow the naming convention of guides and step by steps?

**Comment by Mjeffbrown** [comment]
Both seem reasonable approaches. Thanks @rupertj - "Cover" perhaps my preference as it seems more tied to the idea of a publication, and I don't know if the idea of an "Overview" still confuses people in some of those other contexts (So whether we might need to give Guides and Step By Steps different terminology in the future? An entirely separate discussion)

**Comment by rupertj** [comment]
Thanks all. I've merged it as-is with the name "Publication cover page".
