### ISSUE TITLE
Seeing unment dependencies during install

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_publications#94]
This is trying to install in our main site so our config might lag and we have obviously removed certian config.

> Configuration objects provided by <em class="placeholder">localgov_publicat  
  ions</em> have unmet dependencies: <em class="placeholder">field.field.node  
  .localgov_publication_page.localgov_page_content (paragraphs.paragraphs_typ  
  e.localgov_numbered_text), filter.format.publications (core.entity_view_mod  
  e.media.medium_8_7, core.entity_view_mode.media.responsive_3x2, core.entity  
  _view_mode.media.scale_crop_7_3_large, core.entity_view_mode.media.square)<  
  /em>

**Comment by finnlewis** [comment]
How might we address this? 

Assigning to @rupertj for review.

**Comment by rupertj** [comment]
I think there's two parts to this:

1) As far as I can see, localgov_paragraphs doesn't have an update hook to set up the new numbered text paragraph for people who installed the module before that type was added to the module. We should add that there.

2) We could add the media display modes to the filter format in this module's install hook, so they're not a hard dependency any more.

**Comment by rupertj** [comment]
Once https://github.com/localgovdrupal/localgov_paragraphs/issues/161 and #124 are resolved, the issues raised here should also be resolved.

**Comment by rupertj** [comment]
So the last part of this is adding a dependency on the new release of localgov_paragraphs. I'll make a PR for that now.

**Comment by rupertj** [comment]
@andybroomfield Could you see if this installs cleanly for you now? I'm hoping it should...
