### ISSUE TITLE
Dependancy on ckeditor4?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_publications#95]
Not sure the reasoning here, but maybe this isn't something that should be forced, is there some compatability reasons?

**Comment by rupertj** [comment]
So Publications depends on Footnotes. Footnotes depends on Fakeobjects and Fakeobects depends on CK4.

I've been waiting for footnotes to resolve the issue around working with both D9 and D10 easily, but it's been taking a while to happen, and seeing how D9/CK4 support is a lot less important these days, I've added the patch from https://www.drupal.org/project/footnotes/issues/3222058 to remove the dependency on Fakeobjects and therefore CK4.

@andybroomfield Would you have some time to test the code in the linked PR? It's working fine for me on D10, but I'd like someone else to verify. This'd move us much closer to a beta release too. Thanks :)

**Comment by rupertj** [comment]
Closing this issue in favour of #124, which is about removing footnotes for the moment. This will remove the CK4 dependency.
