### ISSUE TITLE
Publication menu to show what page you are on

### ISSUE THREAD

**Issue by justinepocock** [localgovdrupal/localgov_publications#99]

**Comment by justinepocock** [comment]
Could this have been fixed with #79?

**Comment by justinepocock** [comment]
Nope! Could someone magic in some `active` classes please?

**Comment by justinepocock** [comment]
Got my magic classes, will make them show now

**Comment by rupertj** [comment]
@justinepocock Is this sorted now I added the active class to the right place?

**Comment by justinepocock** [comment]
I need to do the css still but your bit is done

**Comment by rupertj** [comment]
@justinepocock This is the one I was on about yesterday. Does anything still need doing on this or can we close it?
